*** Settings ***
Resource    ../../../configurations/config.resource
*** Variables ***
${UNIT_ITEM}    css:.fa fa-angle-down
${CONTACT_ITEM}    css:a[href="/contactus"]
${BRAND}    css:.brand
${INPUT_SEARCH}    css:.instasearch-term
${SEARCH_BTN}    css:.instasearch-button
${COMPARE_PRODUCT_ITEM}    css:a[href="/compareproducts"]
${WISHLIST_ITEM}    css:a[href="/wishlist"]
${CART_ITEM}    css:a[href="/cart"]
